name: flutter_monorepo

packages:
  - apps/example_abc
  - packages/core/**
  - packages/example_abc/**

scripts:
  coreSetup:
    run: melos exec --concurrency 2 --scope="core_*" "fvm use 3.19.5 && flutter clean && flutter pub get"
  exampleAbcSetupPart1:
    run: melos exec --concurrency 2 --scope="example_abc_storage" "flutter clean && flutter pub get"
  exampleAbcSetupPart2:
    run: melos exec --concurrency 2 --scope="example_abc_*" --ignore="example_abc_storage" "fvm use 3.19.5 && flutter clean && flutter pub get"
  exampleAbcSetupPart3:
    run: melos exec --concurrency 2 --scope="example_abc_storage" "dart run build_runner build --delete-conflicting-outputs"
  exampleAbcAppSetup:
    run: melos exec --scope="example_abc" "fvm use 3.19.5 && flutter clean && flutter pub get"